version: '2'
volumes:
    sensor-data:
services:
  # influxdb:
  #   restart: always
  #   build: ./influxdb
  #   volumes:
  #     - 'sensor-data:/data'
  # grafana:
  #   restart: always
  #   build: ./grafana
  #   ports:
  #     - "80"
  #   volumes:
  #     - 'sensor-data:/data'
  #   environment:
  #       - 'HOME_DASHBOARD_UID=sensor'
  #       - 'GF_PATHS_DATA=/data/grafana'
  #       - 'GF_SERVER_HTTP_PORT=80'
  #       - 'GF_SESSION_PROVIDER=memory'
  #       - 'GF_AUTH_ANONYMOUS_ENABLED=true'
  sensor:
    build: ./sensor
    privileged: true
    restart: always
    volumes:
      - 'sensor-data:/data'
  # telegraf:
  #   build: ./telegraf
  #   restart: always
  #   cap_add:
  #     - SYS_ADMIN
  python_test:
    build: ./python_test
    volumes: 
      - 'sensor-data:/data'
  # mqtt:
  #   image: arm32v6/eclipse-mosquitto
  #   ports:
  #     - "1883:1883"
  #   restart: always
